name: Build and Deploy for Release and Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Add Missing APT Keys
      run: |
        ./scripts/add_apt_keys.sh

    - name: Install Dependencies
      run: |
        ./scripts/install_dependencies.sh

    - name: Install OpenCV
      run: |
        ./scripts/install_opencv.sh

    - name: Configure the Project for Release
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
              -DCMAKE_C_COMPILER=/usr/bin/gcc \
              -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
              -S ${{ github.workspace }} \
              -B ${{ github.workspace }}/build \
              -G "Unix Makefiles"

    - name: Build the Project
      run: |
        cmake --build ${{ github.workspace }}/build --config Release --target all -j 2

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        external_repository: imb410/TrafficEZ-Documentation
        publish_branch: gh-pages
        publish_dir: ./doc/html
        allow_empty_commit: true
        keep_files: false

    - name: Find Built Executable
      id: find_executable
      run: |
        EXECUTABLE_PATH=$(find ${{ github.workspace }}/build/src -type f -name 'TrafficEZ-*' | head -n 1)
        if [[ -z "$EXECUTABLE_PATH" ]]; then
          echo "Executable not found!"
          exit 1
        fi
        EXECUTABLE_NAME=$(basename $EXECUTABLE_PATH)
        TAG_NAME="v${EXECUTABLE_NAME#TrafficEZ-}"
        echo "EXECUTABLE_PATH=$EXECUTABLE_PATH" >> $GITHUB_ENV
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$EXECUTABLE_NAME" >> $GITHUB_ENV

    - name: Test Built Executable
      run: |
        ./scripts/copy_test_files.sh
        cp ${{ env.EXECUTABLE_PATH }} ${{ github.workspace }}/resources/
        export LD_LIBRARY_PATH=${{ github.workspace }}/util/onnxruntime/lib:$LD_LIBRARY_PATH
        ${{ github.workspace }}/resources/$(basename ${{ env.EXECUTABLE_PATH }}) -t

    - name: Create or Update Versioned Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_versioned_release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        gh release view ${{ env.TAG_NAME }} > /dev/null 2>&1 && \
        gh release edit ${{ env.TAG_NAME }} --title ${{ env.RELEASE_NAME }} || \
        gh release create ${{ env.TAG_NAME }} --title ${{ env.RELEASE_NAME }} --notes "Automated release by GitHub Actions"

    - name: Rename Executable for Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: mv ${{ env.EXECUTABLE_PATH }} ${{ github.workspace }}/build/src/TrafficEZ

    - name: Upload Release Asset to Versioned Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        gh release upload ${{ env.TAG_NAME }} ${{ github.workspace }}/build/src/TrafficEZ --clobber

    - name: Upload ONNX Runtime Library
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        gh release upload ${{ env.TAG_NAME }} ${{ github.workspace }}/util/onnxruntime/lib/libonnxruntime.so.1.17.1 --clobber
