name: Code Quality Lint Checks

on:
  push:
    branches:
      - 'release/**'
      - 'dev/**'
  pull_request:
    branches:
      - 'release/**'
      - 'dev/**'

jobs:
  check-clang-formatting:
    name: Clang Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '14'
        check-path: 'src'

  check-header-methods:
    name: Header methods order check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check .h files public before private
        run: python ./test/lint/scan_header_members.py ./src